//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musicapp.DI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicTable
    {
        public int musicID { get; set; }
        public string musicName { get; set; }
        public string musicArtist { get; set; }
        public string musicTypeExtension { get; set; }
        public System.DateTime musicDateUpload { get; set; }
        public string musicGuid { get; set; }
        public string musicType { get; set; }
        public string musicDescription { get; set; }
        public string musicPath { get; set; }
        public string musicFileName { get; set; }
    }
}
