//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musicapp.DI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class musicMusicTable
    {
        public int musicMusicID { get; set; }
        public string musicMusicName { get; set; }
        public string musicMusicArtist { get; set; }
        public string musicMusicTypeExt { get; set; }
        public System.DateTime musicMusicDateUpload { get; set; }
        public string musicMusicGuid { get; set; }
        public string musicMusicType { get; set; }
        public string musicMusicDescription { get; set; }
        public string musicMusicPath { get; set; }
        public string musicMusicFileName { get; set; }
        public string musicMusicFlex { get; set; }
    }
}
