//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musicapp.DI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sampleInstrumentTable
    {
        public int id { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> coverID { get; set; }
        public string sampleName { get; set; }
        public string sampleExtension { get; set; }
        public string sampleTitle { get; set; }
        public string sampleTypeInstrument { get; set; }
        public Nullable<int> sampleSize { get; set; }
        public string sampleGUID { get; set; }
        public string samplePathToFile { get; set; }
        public Nullable<System.DateTime> sampleDateUpload { get; set; }
        public Nullable<int> sampleDownloadQuantity { get; set; }
        public Nullable<bool> sampleAccessPublic { get; set; }
    }
}
