//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musicapp.DI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabulatureTable
    {
        public int id { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> coverID { get; set; }
        public Nullable<int> intrumentID { get; set; }
        public string tabSitePath { get; set; }
        public string tabFolderPath { get; set; }
        public string tabName { get; set; }
        public string tabExtension { get; set; }
        public string tabDescription { get; set; }
        public string tabContent { get; set; }
        public Nullable<System.DateTime> tabUploadTime { get; set; }
        public string tabGuid { get; set; }
    }
}
